# Please don't change

lr0: 0.0032
lrf: 0.2
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
warmup_bias_lr: 0.1
box: 0.05
cls: 0.5
cls_pw: 1.0
obj: 1.0
obj_pw: 1.0
iou_t: 0.20
anchor_t: 4.0

# Augment
# for all
# fl_gamma: 0.0
# hsv_h: 0.5
# hsv_s: 0.5
# hsv_v: 0.5
# degrees: 25
# translate: 0.001
# scale: 0.002
# shear: 15
# perspective: 0.001
# flipud: 0.01
# fliplr: 0.6
# mosaic: 0.1
# mixup: 0.01
# copy_paste: 0.1

# for special cases
fl_gamma: 0.0
hsv_h: 0.5
hsv_s: 0.5
hsv_v: 0.5
degrees: 30
translate: 0.001
scale: 0.005
shear: 20
perspective: 0.005
flipud: 0.01
fliplr: 0.6
mosaic: 0.2
mixup: 0.04
copy_paste: 0.2