# Please don't change

lr0: 0.0032
lrf: 0.2
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
warmup_bias_lr: 0.1
box: 0.05
cls: 0.5
cls_pw: 1.0
obj: 1.0
obj_pw: 1.0
iou_t: 0.20
anchor_t: 4.0

# Augment
fl_gamma: 0.2
hsv_h: 0.5
hsv_s: 0.5
hsv_v: 0.5
degrees: 0.002
translate: 0.001
scale: 0.002
shear: 0.001
perspective: 0.001
flipud: 0.2
fliplr: 0.6
mosaic: 0.001
mixup: 0.001
copy_paste: 0.1